// Subset of Cursor's aiserver.v1.AiService/AvailableModels wire schema.
// Only the fields pi-cursor reads are declared; unknown fields are skipped by
// the protobuf runtime. Field numbers observed from the live response.

// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file aiserver.proto (package aiserver.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file aiserver.proto.
 */
export const file_aiserver: GenFile = /*@__PURE__*/
  fileDesc("Cg5haXNlcnZlci5wcm90bxILYWlzZXJ2ZXIudjEiUwoWQXZhaWxhYmxlTW9kZWxzUmVxdWVzdBIcChR1c2VfbW9kZWxfcGFyYW1ldGVycxgFIAEoCBIbChNkb19ub3RfdXNlX21hcmtkb3duGAcgASgIIkoKF0F2YWlsYWJsZU1vZGVsc1Jlc3BvbnNlEi8KBm1vZGVscxgCIAMoCzIfLmFpc2VydmVyLnYxLlBhcmFtZXRlcml6ZWRNb2RlbCIrCg5Nb2RlbFBhcmFtZXRlchIKCgJpZBgBIAEoCRINCgV2YWx1ZRgCIAEoCSLaAgoUUGFyYW1ldGVyaXplZFZhcmlhbnQSLwoKcGFyYW1ldGVycxgBIAMoCzIbLmFpc2VydmVyLnYxLk1vZGVsUGFyYW1ldGVyEhkKDGRpc3BsYXlfbmFtZRgCIAEoCUgAiAEBEhMKC2lzX21heF9tb2RlGAMgASgIEiIKFWlzX2RlZmF1bHRfbWF4X2NvbmZpZxgEIAEoCEgBiAEBEiYKGWlzX2RlZmF1bHRfbm9uX21heF9jb25maWcYBSABKAhIAogBARIqCh12YXJpYW50X3N0cmluZ19yZXByZXNlbnRhdGlvbhgJIAEoCUgDiAEBQg8KDV9kaXNwbGF5X25hbWVCGAoWX2lzX2RlZmF1bHRfbWF4X2NvbmZpZ0IcChpfaXNfZGVmYXVsdF9ub25fbWF4X2NvbmZpZ0IgCh5fdmFyaWFudF9zdHJpbmdfcmVwcmVzZW50YXRpb24i+wMKElBhcmFtZXRlcml6ZWRNb2RlbBIMCgRuYW1lGAEgASgJEhwKD3N1cHBvcnRzX2ltYWdlcxgKIAEoCEgAiAEBEh4KEXN1cHBvcnRzX21heF9tb2RlGA4gASgISAGIAQESIAoTY29udGV4dF90b2tlbl9saW1pdBgPIAEoDUgCiAEBEi0KIGNvbnRleHRfdG9rZW5fbGltaXRfZm9yX21heF9tb2RlGBAgASgNSAOIAQESIAoTY2xpZW50X2Rpc3BsYXlfbmFtZRgRIAEoCUgEiAEBEh4KEXNlcnZlcl9tb2RlbF9uYW1lGBIgASgJSAWIAQESIgoVc3VwcG9ydHNfbm9uX21heF9tb2RlGBMgASgISAaIAQESMwoIdmFyaWFudHMYHiADKAsyIS5haXNlcnZlci52MS5QYXJhbWV0ZXJpemVkVmFyaWFudEISChBfc3VwcG9ydHNfaW1hZ2VzQhQKEl9zdXBwb3J0c19tYXhfbW9kZUIWChRfY29udGV4dF90b2tlbl9saW1pdEIjCiFfY29udGV4dF90b2tlbl9saW1pdF9mb3JfbWF4X21vZGVCFgoUX2NsaWVudF9kaXNwbGF5X25hbWVCFAoSX3NlcnZlcl9tb2RlbF9uYW1lQhgKFl9zdXBwb3J0c19ub25fbWF4X21vZGUyaQoJQWlTZXJ2aWNlElwKD0F2YWlsYWJsZU1vZGVscxIjLmFpc2VydmVyLnYxLkF2YWlsYWJsZU1vZGVsc1JlcXVlc3QaJC5haXNlcnZlci52MS5BdmFpbGFibGVNb2RlbHNSZXNwb25zZWIGcHJvdG8z");

/**
 * @generated from message aiserver.v1.AvailableModelsRequest
 */
export type AvailableModelsRequest = Message<"aiserver.v1.AvailableModelsRequest"> & {
  /**
   * @generated from field: bool use_model_parameters = 5;
   */
  useModelParameters: boolean;

  /**
   * @generated from field: bool do_not_use_markdown = 7;
   */
  doNotUseMarkdown: boolean;
};

/**
 * Describes the message aiserver.v1.AvailableModelsRequest.
 * Use `create(AvailableModelsRequestSchema)` to create a new message.
 */
export const AvailableModelsRequestSchema: GenMessage<AvailableModelsRequest> = /*@__PURE__*/
  messageDesc(file_aiserver, 0);

/**
 * @generated from message aiserver.v1.AvailableModelsResponse
 */
export type AvailableModelsResponse = Message<"aiserver.v1.AvailableModelsResponse"> & {
  /**
   * @generated from field: repeated aiserver.v1.ParameterizedModel models = 2;
   */
  models: ParameterizedModel[];
};

/**
 * Describes the message aiserver.v1.AvailableModelsResponse.
 * Use `create(AvailableModelsResponseSchema)` to create a new message.
 */
export const AvailableModelsResponseSchema: GenMessage<AvailableModelsResponse> = /*@__PURE__*/
  messageDesc(file_aiserver, 1);

/**
 * @generated from message aiserver.v1.ModelParameter
 */
export type ModelParameter = Message<"aiserver.v1.ModelParameter"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message aiserver.v1.ModelParameter.
 * Use `create(ModelParameterSchema)` to create a new message.
 */
export const ModelParameterSchema: GenMessage<ModelParameter> = /*@__PURE__*/
  messageDesc(file_aiserver, 2);

/**
 * @generated from message aiserver.v1.ParameterizedVariant
 */
export type ParameterizedVariant = Message<"aiserver.v1.ParameterizedVariant"> & {
  /**
   * @generated from field: repeated aiserver.v1.ModelParameter parameters = 1;
   */
  parameters: ModelParameter[];

  /**
   * @generated from field: optional string display_name = 2;
   */
  displayName?: string | undefined;

  /**
   * @generated from field: bool is_max_mode = 3;
   */
  isMaxMode: boolean;

  /**
   * @generated from field: optional bool is_default_max_config = 4;
   */
  isDefaultMaxConfig?: boolean | undefined;

  /**
   * @generated from field: optional bool is_default_non_max_config = 5;
   */
  isDefaultNonMaxConfig?: boolean | undefined;

  /**
   * @generated from field: optional string variant_string_representation = 9;
   */
  variantStringRepresentation?: string | undefined;
};

/**
 * Describes the message aiserver.v1.ParameterizedVariant.
 * Use `create(ParameterizedVariantSchema)` to create a new message.
 */
export const ParameterizedVariantSchema: GenMessage<ParameterizedVariant> = /*@__PURE__*/
  messageDesc(file_aiserver, 3);

/**
 * @generated from message aiserver.v1.ParameterizedModel
 */
export type ParameterizedModel = Message<"aiserver.v1.ParameterizedModel"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: optional bool supports_images = 10;
   */
  supportsImages?: boolean | undefined;

  /**
   * @generated from field: optional bool supports_max_mode = 14;
   */
  supportsMaxMode?: boolean | undefined;

  /**
   * @generated from field: optional uint32 context_token_limit = 15;
   */
  contextTokenLimit?: number | undefined;

  /**
   * @generated from field: optional uint32 context_token_limit_for_max_mode = 16;
   */
  contextTokenLimitForMaxMode?: number | undefined;

  /**
   * @generated from field: optional string client_display_name = 17;
   */
  clientDisplayName?: string | undefined;

  /**
   * @generated from field: optional string server_model_name = 18;
   */
  serverModelName?: string | undefined;

  /**
   * @generated from field: optional bool supports_non_max_mode = 19;
   */
  supportsNonMaxMode?: boolean | undefined;

  /**
   * @generated from field: repeated aiserver.v1.ParameterizedVariant variants = 30;
   */
  variants: ParameterizedVariant[];
};

/**
 * Describes the message aiserver.v1.ParameterizedModel.
 * Use `create(ParameterizedModelSchema)` to create a new message.
 */
export const ParameterizedModelSchema: GenMessage<ParameterizedModel> = /*@__PURE__*/
  messageDesc(file_aiserver, 4);

/**
 * @generated from service aiserver.v1.AiService
 */
export const AiService: GenService<{
  /**
   * @generated from rpc aiserver.v1.AiService.AvailableModels
   */
  availableModels: {
    methodKind: "unary";
    input: typeof AvailableModelsRequestSchema;
    output: typeof AvailableModelsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_aiserver, 0);

